USE [MYDB]
GO

/****** Object:  View [dbo].[HR_TRN_LOG_FOR_TAEMS_LOG]    Script Date: 2026/9/11 下午 05:38:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW  [dbo].[HR_TRN_LOG_FOR_TAEMS_LOG]
AS
SELECT * FROM AUDB.DBO.HR_TRN_LOG A

UNION ALL
SELECT * FROM JPDB.DBO.HR_TRN_LOG A
UNION ALL
SELECT * FROM SGDB.DBO.HR_TRN_LOG A
UNION ALL
SELECT * FROM MYDB.DBO.HR_TRN_LOG A


GO

