USE [MYDB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER View [dbo].[LOAN_LIMIT] AS

	WITH BOOK_RATE AS (
		SELECT
			CCY_CODE AS CCY_CODE ,CONVERSION
			,CASE WHEN CONV.CONVERSION='D/M' THEN BOOK_RATE 
				WHEN CONV.CONVERSION='M/D' THEN 1/BOOK_RATE ELSE BOOK_RATE END AS BOOK_RATE
		FROM WBS_CTB_BOOK_RATE RATE
		JOIN WBS_CTB_RATE_CONVERSION CONV ON RATE.CCY_CODE=CONV.SELL_CCY AND CONV.BUY_CCY='USD'
		WHERE RATE_TYPE='DBU' --AND WBS_CTB_RATE.UPDATE_DATE=CONVERT(VARCHAR(10),GETDATE()-1,112)
		AND RATE.UPDATE_DATE IN (
			SELECT MAX(UPDATE_DATE) FROM WBS_CTB_BOOK_RATE RATE_DATE WHERE RATE_DATE.RATE_TYPE='DBU' GROUP BY RATE_DATE.CCY_CODE
		)
	)
	SELECT 
		LFA.ACCT_NO+SEQ_NO AS ACCOUNT_NBR ,'LNA' AS APPLICATION_CODE ,LFA.CUST_ID AS CUSTOMER_ID
		,REPLICATE('0',4-LEN(LFA.DUTY_SDN))+ LFA.DUTY_SDN AS BRANCH_NBR ,'' AS BRANCH_NAME
		,'' AS ACCOUNT_TYPE_CODE ,'' AS ACCOUNT_TYPE_DESC
		,'' AS OFFICER_NBR ,'' AS OFFICER_NAME
		,'' AS CURRENT_BALANCE ,'' AS AVAILABLE_BALANCE
		,LFA.BGN_LN_DT AS OPENING_DATE ,'' AS CLOSED_DATE ,CASE LFA.STS_CD WHEN '4' THEN '1' ELSE '0' END AS ACCOUNT_STATUS
		,'' AS OVERDRAFT_LIMIT
		,CASE WHEN LFA.PROD_TYP in ('LL','LN') AND LON.TRADE_DATE IS NOT NULL THEN CONVERT(VARCHAR(8), LON.TRADE_DATE, 112)
			  WHEN LFA.PROD_TYP ='NG' AND NEGO.AMEND_DATE IS NOT NULL THEN  CONVERT(VARCHAR(8) ,NEGO.AMEND_DATE, 112)
			  ELSE CONVERT(VARCHAR(8), '19000101', 112) 
		 END AS DATE_OF_LAST_ACTIVITY
		,CAST( CAST(
			CASE WHEN LFA.PROD_TYP IN ('LL','LN') and LON.LON_AMT IS NOT NULL THEN
					LON.LON_AMT*ISNULL((SELECT BOOK_RATE FROM BOOK_RATE WHERE BOOK_RATE.CCY_CODE=LON.LON_CCY),1)
				 WHEN LFA.PROD_TYP ='NG' AND NEGO.NEGO_AMT IS NOT NULL  THEN
					NEGO.NEGO_AMT*ISNULL((SELECT BOOK_RATE FROM BOOK_RATE WHERE BOOK_RATE.CCY_CODE=NEGO.NEGO_CCY),1)
			ELSE 0 END
		 AS DECIMAL(24,2) ) AS NVARCHAR ) AS LOAN_AMT
		/*CONVERT(VARCHAR(10), 0) AS LOAN_AMT, */
		,CAST( CAST(
			CASE WHEN LFA.PROD_TYP in ('LL','LN') AND LON.LON_AMT IS NOT NULL and LFA.BAL_AMT IS NOT NULL THEN
					LON.LON_AMT*ISNULL((SELECT BOOK_RATE FROM BOOK_RATE WHERE BOOK_RATE.CCY_CODE=LON.LON_CCY),1)
						-LFA.BAL_AMT*ISNULL((SELECT BOOK_RATE FROM BOOK_RATE WHERE BOOK_RATE.CCY_CODE=LFA.CURR_TYP),1) 
				 WHEN LFA.PROD_TYP ='NG' AND NEGO.NEGO_AMT IS NOT NULL AND LFA.BAL_AMT IS NOT NULL THEN
					NEGO.NEGO_AMT*ISNULL((SELECT BOOK_RATE FROM BOOK_RATE WHERE BOOK_RATE.CCY_CODE=NEGO.NEGO_CCY),1)
						-LFA.BAL_AMT*ISNULL((SELECT BOOK_RATE FROM BOOK_RATE WHERE BOOK_RATE.CCY_CODE=LFA.CURR_TYP),1)
			  ELSE 0 END
		 AS DECIMAL(24,2) ) AS NVARCHAR ) AS PAYOFF_AMT
		/*CONVERT(VARCHAR(10), 0)  AS PAYOFF_AMT,*/
		,CONVERT(VARCHAR(10), 0) AS ADVANCE_CAPITAL_REPAYMENT_AMT ,CONVERT(VARCHAR(10), 0) AS LOAN_TERM_MONTH ,'' AS MATURITY_DATE
		/*CASE WHEN SUBSTRING(A.TWDUSD,4,7) IN  ('1341207','1361003','1322210') AND LN_FN_ACCT.PROD_TYP IN ('LL','LN') THEN 'Y'
			 ELSE 'N' END AS COLLATERAL_FLAG,*/
		,'Y' AS COLLATERAL_FLAG ,'' AS COLLATERAL_TYPE_CODE ,'' AS COLLATERAL_TYPE_DESC
		,'' AS OPENING_METHOD_CODE ,'' AS OPENING_METHOD_DESC
		,'' AS PRODUCT_CODE ,'' AS PRODUCT_DESC
		,'' AS ACCOUNT_PURPOSE_CODE ,'' AS ACCOUNT_PURPOSE_DESC
		,CONVERT(VARCHAR(10), 0) AS PAST_DUE_AMT ,'' AS DELINQUENT_ACC_FLAG
		,'MYWBS' AS CORE_SYSTEM ,CONVERT(VARCHAR(8), DATEADD(D,-1,GETDATE()), 112) AS PROCESSING_DATE
		
		/*,'' AS SAR_EXCLUDE_FLAG
		,'' AS TRANSFER_FLAG*/

	FROM WBS_LN_FN_ACCT LFA
	LEFT JOIN WBS_LON_INFO LON ON ( LFA.ACCT_NO+LFA.SEQ_NO )=LON.LON_NO
	LEFT JOIN WBS_EXP_NEGO_ITEM NEGO ON ( LFA.ACCT_NO+LFA.SEQ_NO )=NEGO.REF_NO
	WHERE ACC_CD LIKE '13%' 

GO

