USE [MYDB]
GO

/****** Object:  View [dbo].[RAW_CASH_ACCOUNT]    Script Date: 2026/9/11 下午 05:39:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER View [dbo].[RAW_CASH_ACCOUNT] as 

   SELECT 
		ACCT_NO+'000' AS ACCOUNT_NBR ,'SAV' AS APPLICATION_CODE ,CUST_ID AS CUSTOMER_ID
		,REPLICATE('0',4-LEN(exs_brn))+ exs_brn AS BRANCH_NBR ,'' AS BRANCH_NAME
		,'' AS ACCOUNT_TYPE_CODE ,'' AS ACCOUNT_TYPE_DESC 
		,'' AS OFFICER_NBR ,'' AS OFFICER_NAME ,'' AS CURRENT_BALANCE ,'' AS AVAILABLE_BALANCE
		,ACCT_MSTR.OPN_ACCT_DT AS OPENING_DATE ,'' AS CLOSED_DATE ,CASE WHEN ACCT_STS ='A' THEN '0'  ELSE '1' END AS ACCOUNT_STATUS
		,'' AS OVERDRAFT_LIMIT 
		,ACCT_MSTR.CRTE_DT AS DATE_OF_LAST_ACTIVITY
		,'' AS OPENING_METHOD_CODE ,'' AS OPENING_METHOD_DESC 
		,'' AS PRODUCT_CODE ,'' AS PRODUCT_DESC 
		,'' AS ACCOUNT_PURPOSE_CODE ,'' AS ACCOUNT_PURPOSE_DESC
		,'' AS CORE_SYSTEM ,CONVERT(VARCHAR(8), DATEADD(D,-1,GETDATE()), 112) PROCESSING_DATE
    
		--,
		--'' AS SAR_EXCLUDE_FLAG,
		--'' AS TRANSFER_FLAG
    
   FROM WBS_DEP_FN_ACCT_MSTR ACCT_MSTR WHERE ACCT_MSTR.ACCT_NO not like '74%'

GO

