USE [MYDB]
GO

/****** Object:  View [dbo].[RAW_OTHER_TRXN]    Script Date: 2026/9/11 下午 05:39:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



/*  
 * 20200918 納閩分行洗錢防制系統建置 AML  每日批次來源檔(WBS_ACC_VOU_DTL_AML、WBS_RAA_FUNC_INFO、WBS_LN_FN_ACCT)   
 * 20220114 AML本位幣由MYR改為USD 
 * 20221020 排除function code = 029000(Loan Creation)、150000(Outward Remittance Creation)
*/
ALTER View [dbo].[RAW_OTHER_TRXN] AS 
   SELECT 
	   A.TRANSACTION_ID, A.CUSTOMER_ID, A.REFNO AS ACCOUNT_NBR ,IIF( A.CODE like '13%' OR A.CODE LIKE '2252%' OR A.CODE LIKE '1151%'  ,'LNA' ,'SAV') AS APPLICATION_CODE
	   ,CAST(CASE WHEN A.CODE like '13%' AND A.P_AMT < 0  THEN A.P_AMT * -1
			WHEN (A.CODE LIKE '1151%' AND A.I_AMT < 0) OR (A.CODE LIKE '2252%' AND A.I_AMT < 0) THEN A.I_AMT * -1
			WHEN SUBSTRING(A.CODE,1,4) IN ('2317','2327','2545') AND A.P_AMT < 0 THEN A.P_AMT * -1 
			ELSE 0 END AS varchar) AS AMOUNT_IN
	   ,CAST(CASE WHEN A.CODE like '13%' AND A.P_AMT > 0  THEN P_AMT
			WHEN SUBSTRING(A.CODE,1,4) IN ('2317','2327','2545') AND A.P_AMT > 0 THEN P_AMT
			WHEN A.CODE LIKE '2151%'  AND A.I_AMT > 0 THEN I_AMT
			ELSE 0 END AS varchar) AS AMOUNT_OUT
	   ,A.FUNC_CODE AS TRANSACTION_CODE ,B.FUNC_NAME AS TRANSACTION_DESC
	   ,'' AS TELLER_ID ,IIF( A.AGENT_ID = 'B2BOP' ,'4' ,'3') AS TELLER_TYPE ,IIF(A.AGENT_ID = 'B2BOP' ,'Internet banking' ,'Branch Teller') AS TELLER_TYPE_DESC    
	   ,A.TRADE_DATE AS TRANSACTION_DATE ,'' AS CASHED_CHECK_FLAG ,'' AS CHECK_NBR
	   ,'' AS CURRENCY_CODE ,'' AS ORI_AMOUNT_IN ,'' AS ORI_AMOUNT_OUT
	   ,A.CUST_BRANCH AS BRANCH_OF_TRXN ,'MY' AS BANK_NBR
	   ,'MYWBS' AS CORE_SYSTEM ,CONVERT(VARCHAR(10), DATEADD(D,-1,GETDATE()), 20) AS PROCESSING_DATE
	   ,'' AS CONDUCTOR_ID
	   
	   --,
	   --'' AS FOREIGN_CURRENCY_EXCHANGE_FLAG,
	   --'' AS SAR_EXCLUDE_FLAG,
	   --'' AS CASH_FLAG
   
   FROM WBS_ACC_VOU_DTL_AML A 
   LEFT JOIN WBS_RAA_FUNC_INFO B ON A.FUNC_CODE = B.FUNC_CODE
   WHERE RTRIM(LTRIM(A.REFNO)) IN (SELECT  Z.ACCT_NO + RTRIM(LTRIM(Z.SEQ_NO)) FROM WBS_LN_FN_ACCT Z WHERE Z.ACC_CD LIKE '13%')
   AND A.FUNC_CODE not in ('150000')
   AND REFNO NOT IN ( SELECT TRANSACTION_ID FROM RAW_WIRE_TRXN )
   
   UNION ALL 
   
   SELECT 
	   G.TRANSACTION_ID ,G.CUSTOMER_ID ,G.REFNO AS ACCOUNT_NBR
	   ,CASE WHEN G.CODE like '13%' OR G.CODE LIKE '2252%' OR G.CODE LIKE '1151%'  THEN 'LNA' ELSE 'SAV' END AS APPLICATION_CODE
	   ,CAST(CASE WHEN G.CODE like '13%' AND G.P_AMT < 0  THEN G.P_AMT * -1
			WHEN (G.CODE LIKE '1151%' AND G.I_AMT < 0) OR (G.CODE LIKE '2252%' AND G.I_AMT < 0) THEN G.I_AMT * -1
			WHEN SUBSTRING(G.CODE,1,4) IN ('2317','2327','2545') AND G.P_AMT < 0 THEN G.P_AMT * -1 
			ELSE 0 END AS VARCHAR) AS AMOUNT_IN
	   ,CAST(CASE WHEN G.CODE like '13%' AND G.P_AMT > 0  THEN P_AMT
			WHEN SUBSTRING(G.CODE,1,4) IN ('2317','2327','2545') AND G.P_AMT > 0 THEN P_AMT
			WHEN G.CODE LIKE '2151%'  AND G.I_AMT > 0 THEN I_AMT
			ELSE 0 END AS VARCHAR) AS AMOUNT_OUT
	   ,G.FUNC_CODE AS TRANSACTION_CODE ,H.FUNC_NAME AS TRANSACTION_DESC
	   ,'' AS TELLER_ID ,CASE WHEN G.AGENT_ID = 'B2BOP'  THEN '4' ELSE '3' END AS TELLER_TYPE
	        
	   ,CASE WHEN G.AGENT_ID = 'B2BOP'  THEN 'Internet banking' ELSE 'Branch Teller' END AS TELLER_TYPE_DESC
	   ,G.TRADE_DATE AS TRANSACTION_DATE ,'' AS CASHED_CHECK_FLAG ,'' AS CHECK_NBR 
	   ,'' AS CURRENCY_CODE ,'' AS ORI_AMOUNT_IN ,'' AS ORI_AMOUNT_OUT
	   ,G.CUST_BRANCH AS BRANCH_OF_TRXN ,'MY' AS BANK_NBR
	   ,'MYWBS' AS CORE_SYSTEM ,CONVERT(VARCHAR(10), DATEADD(D,-1,GETDATE()), 20) AS PROCESSING_DATE
	   ,'' AS CONDUCTOR_ID
	   
	   --,
	   --'' AS FOREIGN_CURRENCY_EXCHANGE_FLAG,
	   --'' AS SAR_EXCLUDE_FLAG,
	   --'' AS CASH_FLAG
    
   FROM WBS_ACC_VOU_DTL_AML G 
   LEFT JOIN WBS_RAA_FUNC_INFO H ON G.FUNC_CODE = H.FUNC_CODE
   WHERE SUBSTRING(G.CODE,1,4) IN ('2317','2327','2545')
   AND G.FUNC_CODE not in ('029000','150000')
   AND REFNO NOT IN ( SELECT TRANSACTION_ID FROM RAW_WIRE_TRXN )

GO

