USE [MYDB]
GO

/****** Object:  View [dbo].[SG_FX_TD_CERTIFICATE]    Script Date: 2026/9/11 下午 05:41:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER View [dbo].[SG_FX_TD_CERTIFICATE] as 

   SELECT 
   ACCT_NO AS ACCOUNT_NBR,
   'COD' AS APPLICATION_CODE,
   CUST_ID AS CUSTOMER_ID,
   REPLICATE('0',4-LEN(DUTY_SDN))+ DUTY_SDN  AS BRANCH_NBR,
   '' AS BRANCH_NAME,
   '' AS ACCOUNT_TYPE_CODE,
   '' AS ACCOUNT_TYPE_DESC,
   '' AS OFFICER_NBR,
   '' AS OFFICER_NAME,
   '' AS CURRENT_BALANCE,
   '' AS AVAILABLE_BALANCE,
   OPN_DT AS OPENING_DATE,
   '' AS CLOSED_DATE, 
   CASE WHEN ACCT_STS = '00' THEN '0' WHEN ACCT_STS = '01' THEN '1' END AS ACCOUNT_STATUS,
   '' AS OVERDRAFT_LIMIT,
   LST_TXN_DT AS DATE_OF_LAST_ACTIVITY,
   '' AS TERM_MONTH,
   '' AS MATURITY_DATE,
   '' AS OPENING_METHOD_CODE,
   '' AS OPENING_METHOD_DESC,
   '' AS PRODUCT_CODE,
   '' AS PRODUCT_DESC,
   '' AS ACCOUNT_PURPOSE_CODE,
   '' AS ACCOUNT_PURPOSE_DESC,
   'MYWBS' AS CORE_SYSTEM,
   CONVERT(VARCHAR(8), DATEADD(D,-1,GETDATE()), 112) AS PROCESSING_DATE
   FROM WBS_DEP_FN_ACCT_SEC   WHERE ACC_CD IN ('2327','2545')

GO

