USE [MYDB]
GO

/****** Object:  View [dbo].[vw_RISKSYS_WBS_VW_COL_FAC_LON]    Script Date: 2026/9/11 下午 05:47:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*
SELECT * FROM MYDB.dbo.vw_RISKSYS_WBS_VW_COL_FAC_LON
*/
ALTER VIEW [dbo].[vw_RISKSYS_WBS_VW_COL_FAC_LON]
AS
/*
使用系統: RISKSYS 風險管理系統
程式名稱: MYDB.dbo.vw_RISKSYS_WBS_VW_COL_FAC_LON
程式說明: 查詢HKWBS系統擔保品連結放款明細, RISKSYS系統資料同步使用。
參考程式: WBS Source: ODSP.ODDBP01.dbo.WBS_VW_COL_FAC_LON / WBS IT: 張書坤
開發人員: RISKSYS IT: 王勝玄 / MYWBS IT: 王盛禾
開發日期: 2022/03/17
修改記錄:
2022/04/29 王勝玄 林佳慧 提案單IT20202202161057 彙整海外分行(新加坡分行、布里斯本分行、東京分行、納閔分行)擔保品(含存款)資訊需求。
           BRN_NO欄位值由0925改為MY。
*/

SELECT CONVERT(varchar(8),(SELECT BATCH_BUSINESS_DATE FROM dbo.WBS_CTB_BUSINESS_DATE)) AS DATADATE, --資料日期
       --CONVERT(varchar(10),'0925') AS BRN_NO, --分行代碼: MY分行預設值0925
       CONVERT(varchar(10),'MY') AS BRN_NO, --分行代碼: MY分行預設值MY
       CONVERT(varchar(24),CIF.CUSTOMER_GLOBAL_ID) AS CUSTOMER_NO, --客戶ID
       CONVERT(varchar(17),COL.COL_INFO_NO) AS COL_NO, --擔保品編號
       CONVERT(decimal(18,0),FAC.FACILITY_NO) AS FACILITY_NO, --授信案號
       CONVERT(decimal(10,0),ND1.NODE_TYPE) AS NODE_TYPE, --節點類型
       CONVERT(varchar(512),ND1.NODE_PATH) AS NODE_PATH, --節點編號
       CONVERT(varchar(100),ND1.FAC_SUBJECT_CODE) AS FAC_SUBJECT_CODE, --額度代碼
       CONVERT(varchar(128),SCD.NAME) AS FACILITY_NAME, --名稱
       CONVERT(varchar(20),T.ACCT_NO) AS ACCT_NO, --帳號
       CONVERT(varchar(3),T.CCY) AS ACCT_CURRENCY, --幣別
       CONVERT(decimal(18,3),T.BAL_AMT) AS AMT, --金額
       CONVERT(decimal(5,2),CL.COL_PERCENTAGE) AS PLEDGE_RATE, --擔保成數
       CONVERT(decimal(5,2),CL.DISTRIBUTE_RATE) AS ASSIGN_RATE, --分配比率
       CONVERT(varchar(1),CASE WHEN (FAP.SYNDLON_TYPE IS NULL AND FAR.SYNDLON_TYPE IS NULL AND FG.SYNDLON_TYPE IS NULL) THEN '' ELSE 'Y' END) AS SYNDLON_FLAG, --聯貸案註記
       CONVERT(varchar(12),ISNULL(CIF.RM1_PCC,'')) AS PRFT_CNTR --PCC     
  FROM dbo.WBS_COL_INFO COL
  JOIN dbo.WBS_COL_TYPE_CD CD ON CD.COL_TYPE_SEQ = COL.COL_TYPE_SEQ
  JOIN dbo.WBS_CIF_CUST_INFO CIF ON CIF.CIF_CUST_INFO_SEQ = COL.CIF_CUST_INFO_SEQ
  JOIN dbo.WBS_COL_FAC_LINK CL ON CL.COL_INFO_SEQ = COL.COL_INFO_SEQ
  JOIN dbo.WBS_FAC_NODE ND ON ND.FAC_NODE_SEQ = CL.FAC_NODE_SEQ
  JOIN dbo.vw_RISKSYS_WBS_CFND CFND ON CFND.ROOT_CODE = ND.FAC_NODE_SEQ
  JOIN dbo.WBS_FAC_NODE ND1 ON ND1.FAC_NODE_SEQ = CFND.FAC_NODE_SEQ
  JOIN dbo.WBS_FAC_INFO FAC ON FAC.FAC_INFO_SEQ = ND1.FAC_INFO_SEQ
  JOIN dbo.WBS_FAC_SUBJECT_CODE_CD SCD ON SCD.CODE = ND1.FAC_SUBJECT_CODE
  JOIN dbo.WBS_FAC_TXN T ON T.FAC_NODE_SEQ = ND1.FAC_NODE_SEQ
  LEFT JOIN dbo.WBS_FAC_GEN FG ON FG.FAC_NODE_SEQ = ND1.PARENT_NODE_SEQ
  LEFT JOIN dbo.WBS_FAC_AP FAP ON FAP.FAC_NODE_SEQ = ND.PARENT_NODE_SEQ
  LEFT JOIN dbo.WBS_FAC_AR FAR ON FAR.FAC_NODE_SEQ = ND.PARENT_NODE_SEQ
 WHERE T.BAL_AMT > 0


GO

